apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: ghcr.io/krutik2710/ai-platform-api
    newTag: sha-b1c61fc