apiVersion: v1
kind: Service

metadata:
  name: ai-platform-frontend
  namespace: ai-platform

spec:
  type: ClusterIP

  selector:
    app: ai-platform-frontend

  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
